### ISSUE TITLE
json 값이 Boolean인 경우 그대로 Boolean 값을 반환하도록 수정한다

### ISSUE THREAD

**Issue by gwiyeomgo** [bettercode-oss/gin-middleware-xss#1]
# 배경
json 값이 Boolean인 경우 살균하면 string 값으로 출력 된다

# 완료목표
json 값이 Boolean인 경우 그대로 Boolean 값을 반환하도록 수정한다

**Comment by YooYoungmo** [comment]
담당자를 @gwiyeomgo 님으로 할당 합니다.

**Comment by ahnyounghoe** [comment]
@gwiyeomgo 살균이란 표현은 어디에서 유래한 건가요?

**Comment by gwiyeomgo** [comment]
@ahnyounghoe 
sanitizer (소독제) 가 살균하는 것처럼 XSS 공격을 제거하는 것을 살균이라고 표현했어요. 

![image](https://user-images.githubusercontent.com/77624394/226925551-fb5d8c1b-6b61-43cb-bb62-a81f1065cee4.png)

**Comment by ahnyounghoe** [comment]
@gwiyeomgo 구체적으로 어떤 라이브러리에서 쓰는 은유(작명)인가요?

**Comment by gwiyeomgo** [comment]
아 sanitizer 단어를 
https://github.com/dvwright/xss-mw/blob/7a0dab86d8f63202fbeb1023838a538132de1102/xss.go#L233
여기서 사용해요

**Comment by ahnyounghoe** [comment]
@gwiyeomgo XssMw 에서 정의한 이름인가요?

**Comment by gwiyeomgo** [comment]
@ahnyounghoe 
XssMw 라이브러리에 README.md 에는 sanitize 에 대한 명확한 설명은 없습니다. 
코드를 보고 sanitize 함수가 XXS 공격을 제거한다고 추측했어요.

**Comment by YooYoungmo** [comment]
@gwiyeomgo @ahnyounghoe  XssSanitizer 제가 코드 리뷰 과정에서 제안한 표현인데요.
작명에 대한 배경은 두 가지 입니다.
1. [OWASP Go SCP 가이드](https://github.com/OWASP/Go-SCP/blob/master/dist/go-webapp-scp.pdf)
가이드에 Sanitization 이라는 표현이 등장합니다.
> Sanitization
Sanitization refers to the process of removing or replacing submitted data. When dealing with data, after the proper validation checks have been made, sanitization is an additional step that is usually taken to strengthen data safety.

2. [bluemonday](https://github.com/microcosm-cc/bluemonday)
Golang 에서 XSS 공격에 많이 사용하는 라이브러리 입니다. 
저희가 만든 미들웨어에서도 내부에서는 bluemonday 쓰고 있습니다.
bluemonday 에서도 sanitizer 표현을 쓰고 있습니다.
> bluemonday is a HTML sanitizer implemented in Go. It is fast and highly configurable.

bluemonday에서 제공하는 함수 이름도 쓰고 있습니다.
```go
func main() {
	// Do this once for each unique policy, and use the policy for the life of the program
	// Policy creation/editing is not safe to use in multiple goroutines
	p := bluemonday.UGCPolicy()

	// The policy can then be used to sanitize lots of input and it is safe to use the policy in multiple goroutines
	html := p.Sanitize(
		`<a onblur="alert(secret)" href="http://www.google.com">Google</a>`,
	)

	// Output:
	// <a href="http://www.google.com" rel="nofollow">Google</a>
	fmt.Println(html)
}
```

**Comment by ahnyounghoe** [comment]
@YooYoungmo 고맙습니다. @gwiyeomgo 다자간 대화로 작명의 유래가 제대로 밝혀졌네요. 😀
